language: r
r: bioc-release
warnings_are_errors: false
cache: packages
r_build_args: "--no-manual --no-resave-data"
r_check_args: "--no-build-vignettes --no-manual --timings"
notifications:
  slack:
    secure: N0Thi+Zx4q4szCYq5+hEkwCydTrtI6aQR5xQgNxevIpuoU5NxEf5qv57w2+KtqyoHFORoLHXVGg8DZO89dad0/hycFDVFCRmSJlwICZMMMSHVrI9qrqVRNnOazlnF38RjMEqH4w2Dx8rRI02PI6sfBebcrrsDC9lHjL17untrRz5QznvuW/GFgZyJ9r4GH6v0UI5DGKR3B432lzmhkuGR4Yk1tT4mr9G2ZBBjKJa/UKe+xZW8LHmCMnlJGhb/lGzIH7ugBRZsE5DdCm/gYSiOtVlCs3UQCAQVGcXfbtrt3XnqI3qcQG1aYE2R+nwhAYNcr+Wnmjq1uw9kFBLgfBUeltdBP3oS5y7JFqpqkjioo34fIyNzsFGkWUGwm0AC6xj7n0lWP0DLM0/cCBAEmj3NlL/QSNYMkVd00dJIapl4pNPhaOI8G2luNaxNyNbZ6voE4AaagOA8eQnTqSIurf91kWAXfk/EGeV0hZ4haRuqmG/DVzUiVA0wsyGc2Whf4DtJHCvPa38aCqsWNi1OMyz2Q8otHDr6XDM5wZIGvON0OiV/BiJLixoYGcOzsIPh8Gt8gRzyNChsQJmzFafFxufVeDf2aLEq97Odamnh8OYAHQVjBNB8t6ZN+3yThuOxiSqM349ts0oK0WCGliV0MCvr1q6sUh1rFnVqvSpmaUZlMg=
